// x2_mod_def_unaqu,prc_onunaquire
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onunaquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("x2_mod_def_unaqu", OBJECT_SELF);
    ExecuteScript("prc_onunaquire", OBJECT_SELF);
}
