// nw_o0_dying,prc_ondying
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdying event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("nw_o0_dying", OBJECT_SELF);
    ExecuteScript("prc_ondying", OBJECT_SELF);
}
