//::///////////////////////////////////////////////
//:: Name ohs_hen_attack
//:: Copyright (c) 2004 OldMansBeard
//:://////////////////////////////////////////////
/*
   OnPhysicalAttacked handler for OHS henchmen.
   This is a simplified & modifed form of Bioware's nw_ch_ac5
*/
//:://////////////////////////////////////////////
//:: Created By:    OldMansBeard
//:: Created On:    2004-12-10
//:: Last Modified: 2004-12-14
//:://////////////////////////////////////////////

#include "ohs_i0_combat"
#include "inc_debug_dac"
#include "nw_i0_plot"

void main()
{
  //debugVarObject("ohs_hen_attack", OBJECT_SELF);
  //debugVarInt(GetName(GetFirstPC()) + " reaction", GetReputation(GetFirstPC(), OBJECT_SELF));
  
  SpeakString("NW_I_WAS_ATTACKED", TALKVOLUME_SILENT_TALK);

  if (GetAssociateState(NW_ASC_IS_BUSY)) return;
  else if (GetAssociateState(NW_ASC_MODE_STAND_GROUND)) return;
  else if (GetIsObjectValid(GetAttackTarget())) return;
  else if (GetIsObjectValid(GetAttemptedSpellTarget())) return;
  else if (!GetIsObjectValid(GetLastAttacker())) return;
  else
  {
    SetCommandable(TRUE);
    object oEnemy;
    if (GetAssociateState(NW_ASC_MODE_DEFEND_MASTER))
    {
      oEnemy = GetLastAttacker(GetMaster());
    }
    else
    {
      oEnemy = OBJECT_INVALID;
    }
    OHSCombatRound(oEnemy);
  }
}



////////////////////////////////////////////////////////////////////////////////////////
//                                                                                    //
// (C) 2004, 2005, 2006 by bob@minors-ranton.fsnet.co.uk (aka "OldMansBeard")         //
//                                                                                    //
// The NWScript source code file to which this notice is attached is copyright.       //
// It may not be published or passed to a third party in part or in whole modified    //
// or unmodified without the express consent of the copyright holder.                 //
//                                                                                    //
// NWN byte code generated by compiling it or variations of it may be published       //
// or otherwise distributed notwithstanding under the terms of the Bioware EULA.      //
//                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////
