// x2_mod_def_act,prc_onactivate
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onactivateitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
//    ExecuteScript("x2_mod_def_act", OBJECT_SELF);
    ExecuteScript("prc_onactivate", OBJECT_SELF);
}
